# Generated by Django 4.1.5 on 2023-01-31 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='url',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
    ]
