# Generated by Django 4.1.5 on 2023-01-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_room_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='url',
            field=models.URLField(),
        ),
    ]
