version: "3"


volumes:
  postgres:
  static_volume:

networks:
  internal:

services:
  db:
    image: postgres:11
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata:rw
    env_file:
      - .env
    networks:
      - internal
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data/pgdata

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
    - ./storage/redis/data:/data
    networks:
      - internal
    env_file:
      - ./.env 

  web:
    build: .
    restart: always
    volumes:
      - static_volume:/djangosite/app/static/
    ports:
      - "8000:8000"
    networks:
      - internal
    env_file:
      - ./.env 


  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/var/html/static/
    networks:
      - internal
    depends_on:
      - web