# Generated by Django 4.1.5 on 2023-01-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls_for_ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempacc',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
