# Generated by Django 4.1.5 on 2023-02-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls_for_ticket', '0003_alter_tempacc_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempacc',
            name='clean_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
